[project]
name = "deep-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "openai>=2.14.0",
    "pydantic-settings>=2.12.0",
    "tavily>=1.1.0",
]
